dut_settings:
  communication: spi
  crc_bits: 8
  dut_bytes: 6
  frequency: 1500
  is_rotary: true
  multiturn_bits: 0
  phase: 1
  polarity: 0
  resolution: 2097152
  singleturn_bits: 21
  status_bits: 2
ref_settings:
  interpolation_factor: 100
  number_of_periods: 11840
