orbis_preset = {
    "position_offset": {
        "value": 0,
        "bank": 3,
        "address": 0x00,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_set": {
        "value": 0,
        "bank": 3,
        "address": 0x14,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_apply": {
        "value": 0x6D,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "detailed_status":  # detailed status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x4A,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "persistent_status":  # persistent status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x58,
        "length": 4,
        "is_signed": 1,
        "execute": 1,
    },
    "partial_arc_length": {
        "value": 0x04,
        "bank": 1,
        "address": 0x49,
        "length": 2,
        "is_signed": 0,
        "execute": 0,
    },
    "start_calibration":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0x41,
        "bank": 1,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_increment":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0,
        "bank": 4,
        "address": 0x00,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_status":  # self-calibration status register
    {
        "value": 0,
        "bank": 4,
        "address": 0x00,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_ring_ecc":  # ring eccentricity shift
    {
        "value": 0,
        "bank": 4,
        "address": 0xC8,
        "length": 2,
        "is_signed": 0,
        "execute": 0,
    },
    "sensor_temperature": {
        "value": 0,
        "bank": 0,
        "address": 0x4E,
        "length": 2,
        "is_signed": 1,
        "execute": 1,
    },
    "rotational_speed": {
        "value": 0,
        "bank": 0,
        "address": 0x54,
        "length": 4,
        "is_signed": 1,
        "execute": 0,
    },
    "counting_direction": {
        "value": 0,
        "bank": 0,
        "address": 0x19,
        "length": 1,
        "is_signed": 0,
        "execute": 0,
    },
    "save_to_flash": {
        "value": 0x63,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "factory_reset": {
        "value": 0x72,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "signal_level": {
        "value": 0,
        "bank": 0,
        "address": 0x50,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
}

artos_preset = {
    "position_offset": {
        "value": 0,
        "bank": 3,
        "address": 0x00,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_apply": {
        "value": 0x6D,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_set": {
        "value": 0,
        "bank": 3,
        "address": 0x14,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "detailed_status":  # detailed status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x4A,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "persistent_status":  # persistent status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x58,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "partial_arc_length": {
        "value": 0x04,
        "bank": 1,
        "address": 0x49,
        "length": 2,
        "is_signed": 0,
        "execute": 0,
    },
    "start_calibration":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0x41,
        "bank": 1,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_increment":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0,
        "bank": 4,
        "address": 0x00,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_status":  # self-calibration status register
    {
        "value": 0,
        "bank": 4,
        "address": 0x00,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_ring_ecc":  # ring eccentricity shift
    {
        "value": 0,
        "bank": 4,
        "address": 0x06,
        "length": 2,
        "is_signed": 0,
        "execute": 1,
    },
    "sensor_temperature": {
        "value": 0,
        "bank": 0,
        "address": 0x4E,
        "length": 2,
        "is_signed": 1,
        "execute": 1,
    },
    "rotational_speed": {
        "value": 0,
        "bank": 0,
        "address": 0x54,
        "length": 4,
        "is_signed": 1,
        "execute": 1,
    },
    "counting_direction": {
        "value": 0,
        "bank": 3,
        "address": 0x19,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "save_to_flash": {
        "value": 0x63,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "signal_level": {
        "value": 0,
        "bank": 0,
        "address": 0x50,
        "length": 4,
        "is_signed": 0,
        "execute": 0,
    },
    "factory_reset": {
        "value": 0x72,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
}

aksim2_preset = {
    "position_offset": {
        "value": 0,
        "bank": 3,
        "address": 0x00,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_set": {
        "value": 0,
        "bank": 3,
        "address": 0x14,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_apply": {
        "value": 0x6D,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "detailed_status":  # detailed status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x4A,
        "length": 2,
        "is_signed": 0,
        "execute": 1,
    },
    "persistent_status":  # persistent status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x2C,
        "length": 2,
        "is_signed": 1,
        "execute": 1,
    },
    "partial_arc_length": {
        "value": 360,
        "bank": 1,
        "address": 0x19,
        "length": 2,
        "is_signed": 0,
        "execute": 1,
    },
    "start_calibration":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0x41,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_increment":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0,
        "bank": 0,
        "address": 0x52,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_status":  # self-calibration status register
    {
        "value": 0,
        "bank": 0,
        "address": 0x52,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_ring_ecc":  # ring eccentricity shift
    {
        "value": 0,
        "bank": 0,
        "address": 0x1B,
        "length": 2,
        "is_signed": 1,
        "execute": 1,
    },
    "sensor_temperature": {
        "value": 0,
        "bank": 0,
        "address": 0x4C,
        "length": 2,
        "is_signed": 1,
        "execute": 1,
    },
    "rotational_speed": {
        "value": 0,
        "bank": 0,
        "address": 0x50,
        "length": 2,
        "is_signed": 1,
        "execute": 1,
    },
    "counting_direction": {
        "value": 0,
        "bank": 0,
        "address": 0x19,
        "length": 1,
        "is_signed": 0,
        "execute": 0,
    },
    "save_to_flash": {
        "value": 0xCD,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "signal_level": {
        "value": 0,
        "bank": 0,
        "address": 0x4E,
        "length": 2,
        "is_signed": 0,
        "execute": 1,
    },
    "factory_reset": {
        "value": 0x72,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
}

aksim4_preset = {
    "position_offset": {
        "value": 0,
        "bank": 0,
        "address": 0x00,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_set": {
        "value": 0,
        "bank": 0,
        "address": 0x14,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_apply": {
        "value": 0x6D,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "detailed_status":  # detailed status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x4A,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "persistent_status":  # persistent status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x58,
        "length": 4,
        "is_signed": 1,
        "execute": 1,
    },
    "partial_arc_length": {
        "value": 360,
        "bank": 4,
        "address": 0x04,
        "length": 2,
        "is_signed": 0,
        "execute": 1,
    },
    "start_calibration":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0x41,
        "bank": 1,
        "address": 0x41,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_increment":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0,
        "bank": 0,
        "address": 0x00,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_status":  # self-calibration status register
    {
        "value": 0,
        "bank": 0,
        "address": 0x00,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_ring_ecc":  # ring eccentricity shift
    {
        "value": 0,
        "bank": 0,
        "address": 0x06,
        "length": 2,
        "is_signed": 0,
        "execute": 1,
    },
    "sensor_temperature": {
        "value": 0,
        "bank": 0,
        "address": 0x4E,
        "length": 2,
        "is_signed": 1,
        "execute": 1,
    },
    "rotational_speed": {
        "value": 0,
        "bank": 0,
        "address": 0x54,
        "length": 4,
        "is_signed": 1,
        "execute": 1,
    },
    "counting_direction": {
        "value": 0,
        "bank": 0,
        "address": 0x19,
        "length": 1,
        "is_signed": 0,
        "execute": 0,
    },
    "save_to_flash": {
        "value": 0x63,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "signal_level": {
        "value": 0,
        "bank": 0,
        "address": 0x50,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "factory_reset": {
        "value": 0x72,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
}

asko_biss_preset = {
    "position_offset": {
        "value": 0,
        "bank": 3,
        "address": 0x00,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_set": {
        "value": 0,
        "bank": 3,
        "address": 0x14,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_apply": {
        "value": 0x6D,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "detailed_status":  # detailed status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x4A,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "persistent_status":  # persistent status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x58,
        "length": 4,
        "is_signed": 1,
        "execute": 1,
    },
    "partial_arc_length": {
        "value": 360,
        "bank": 4,
        "address": 0x04,
        "length": 2,
        "is_signed": 0,
        "execute": 1,
    },
    "start_calibration":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0x41,
        "bank": 1,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_increment":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0,
        "bank": 4,
        "address": 0x00,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_status":  # self-calibration status register
    {
        "value": 0,
        "bank": 4,
        "address": 0x00,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_ring_ecc":  # ring eccentricity shift
    {
        "value": 0,
        "bank": 4,
        "address": 0x06,
        "length": 2,
        "is_signed": 1,
        "execute": 0,
    },
    "sensor_temperature": {
        "value": 0,
        "bank": 0,
        "address": 0x4E,
        "length": 2,
        "is_signed": 1,
        "execute": 1,
    },
    "rotational_speed": {
        "value": 0,
        "bank": 0,
        "address": 0x54,
        "length": 4,
        "is_signed": 1,
        "execute": 0,
    },
    "counting_direction": {
        "value": 0,
        "bank": 0,
        "address": 0x19,
        "length": 1,
        "is_signed": 0,
        "execute": 0,
    },
    "save_to_flash": {
        "value": 0x63,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "factory_reset": {
        "value": 0x72,
        "bank": 0,
        "address": 0x49,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "signal_level": {
        "value": 0,
        "bank": 0,
        "address": 0x50,
        "length": 4,
        "is_signed": 1,
        "execute": 1,
    },
}

asko_encolink_preset = {
    "position_offset": {
        "value": 0,
        "bank": 3,
        "address": 0x80,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_set": {
        "value": 0,
        "bank": 3,
        "address": 0x94,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "multiturn_apply": {
        "value": 0x6D,
        "bank": 0,
        "address": 0xBD,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "detailed_status":  # detailed status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x0A,
        "length": 4,
        "is_signed": 0,
        "execute": 0,
    },
    "persistent_status":  # persistent status enkoderja
    {
        "value": 0,
        "bank": 0,
        "address": 0x0A,
        "length": 4,
        "is_signed": 1,
        "execute": 1,
    },
    "partial_arc_length": {
        "value": 360,
        "bank": 0,
        "address": 0xC4,
        "length": 2,
        "is_signed": 0,
        "execute": 1,
    },
    "start_calibration":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0x41,
        "bank": 1,
        "address": 0xBD,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_increment":  # register self-calibration bitov, ki se inkrementirata po samokalibraciji
    {
        "value": 0,
        "bank": 4,
        "address": 0xC0,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_status":  # self-calibration status register
    {
        "value": 0,
        "bank": 4,
        "address": 0xC0,
        "length": 4,
        "is_signed": 0,
        "execute": 1,
    },
    "self_cal_ring_ecc":  # ring eccentricity shift
    {
        "value": 0,
        "bank": 4,
        "address": 0xC8,
        "length": 2,
        "is_signed": 0,
        "execute": 0,
    },
    "sensor_temperature": {
        "value": 0,
        "bank": 0,
        "address": 0x00,
        "length": 2,
        "is_signed": 1,
        "execute": 1,
    },
    "rotational_speed": {
        "value": 0,
        "bank": 0,
        "address": 0x06,
        "length": 4,
        "is_signed": 1,
        "execute": 1,
    },
    "counting_direction": {
        "value": 0,
        "bank": 0,
        "address": 0x19,
        "length": 1,
        "is_signed": 0,
        "execute": 0,
    },
    "save_to_flash": {
        "value": 0x63,
        "bank": 0,
        "address": 0xBD,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "factory_reset": {
        "value": 0x72,
        "bank": 0,
        "address": 0xBD,
        "length": 1,
        "is_signed": 0,
        "execute": 1,
    },
    "signal_level": {
        "value": 0,
        "bank": 0,
        "address": 0x02,
        "length": 4,
        "is_signed": 1,
        "execute": 1,
    },
}
